"""Editable teaching content reconstructed from the original Neovim field guide.

Keep this human-written material concise, practical, and independent of a plugin's
current key names. The generator inserts current configuration mappings separately.
"""

CORE_SECTIONS = [
    ("Move precisely, then act", "Normal mode • motions work after d / c / y / v", [
        ("Character, line & screen", [("h j k l", "Left, down, up, right."), ("0 / ^ / $", "Line start / first nonblank / line end."), ("H M L", "Top / middle / bottom visible screen line."), ("Ctrl-u / Ctrl-d", "Half-page up / down."), ("zt zz zb", "Place cursor line at top / center / bottom.")]),
        ("Words, paragraphs & file", [("w b e", "Next word start / previous word start / word end."), ("W B E", "Same by whitespace-separated WORD."), ("{ }", "Previous / next paragraph."), ("gg / G", "First / last line of the file."), (":42 / 42G", "Go to line 42."), ("%", "Jump between matching delimiters."), ("Ctrl-o / Ctrl-i", "Older / newer jump location.")]),
        ("Find on one line", [("f x / F x", "Find character x forward / backward; land on it."), ("t x / T x", "Move until just before x, forward / backward."), ("; / ,", "Repeat the latest find in the same / opposite direction."), ("* / #", "Search word under cursor forward / backward.")]),
    ], "Counts repeat the next command: 3w moves three words; 5dd deletes five lines; d2j deletes the current plus next two lines; 2ci( changes inside the next two parenthesized areas."),
    ("Edit with operators, text objects & registers", "Normal / Visual / Insert modes", [
        ("Operators: the verbs", [("d", "Delete (also copies to a register)."), ("c", "Change: delete, then enter Insert mode."), ("y", "Yank: copy to a register."), ("> / <", "Indent right / left; add = to auto-indent."), ("g~ / gu / gU", "Toggle case / lower / upper."), ("=", "Auto-format indentation using filetype rules.")]),
        ("Text objects: the nouns", [("iw / aw", "Inner word / word including surrounding space."), ("i\" / a\"", "Inside quotes / quotes plus contents."), ("i( i[ i{", "Inside parentheses / brackets / braces."), ("a( a[ a{", "Object including delimiters."), ("ip / ap", "Inner paragraph / paragraph plus blank space.")]),
        ("Insert, paste & repeat", [("i I / a A", "Insert at cursor / first text; append / line end."), ("o / O", "Open a line below / above and insert."), ("p / P", "Paste after / before cursor or line."), ("u / Ctrl-r", "Undo / redo."), (".", "Repeat the last change.")]),
    ], "Read keys as a sentence: dw deletes to the next word; ci\" changes inside quotes; ya( copies parentheses and contents. Fast line forms: dd, cc, yy, >>."),
    ("Search, replace, save & get unstuck", "Search is local • Telescope searches projects", [
        ("Search within this file", [("/text Enter / ?text Enter", "Search forward / backward."), ("n / N", "Next / previous match."), (":noh", "Clear highlighting, not the search pattern."), ("/\\cword / /\\Cword", "Force case-insensitive / case-sensitive search."), ("/\\Vliteral", "Search punctuation literally."), ("q/", "Open editable search history.")]),
        ("Substitute", [(":s/old/new/", "Replace first match on this line."), (":s/old/new/g", "Replace every match on this line."), (":%s/old/new/gc", "Whole file: replace all and confirm each."), (":'<,'>s/old/new/g", "Replace only the current visual selection."), ("& / :%&", "Repeat the latest substitute on this line / whole file.")]),
        ("Help & recovery", [(":help {topic}", "Open built-in documentation."), (":map / :nmap / :imap", "Inspect mappings by mode."), (":checkhealth", "Diagnose Neovim, providers, and plugins."), (":messages", "Show recent notifications and errors."), (":w :q :wq :q!", "Save / quit / save+quit / force quit.")]),
    ], "Your setup uses ignorecase + smartcase: lowercase searches ignore case; adding any capital makes the search case-sensitive."),
    ("Buffers, windows, tabs & lists", "Think: buffer = file in memory • window = view", [
        ("Buffers", [(":ls / :buffers", "List open buffers."), (":b name", "Switch by partial buffer name."), (":bnext / :bprev", "Next / previous buffer."), (":bdelete", "Close buffer without necessarily closing its window.")]),
        ("Windows", [(":split / :vsplit", "Horizontal / vertical split."), ("Ctrl-w h/j/k/l", "Move focus between splits."), ("Ctrl-w c / Ctrl-w o", "Close current / keep only current window."), ("Ctrl-w =", "Equalize split sizes.")]),
        ("Tabs, folds & lists", [(":tabnew / gt / gT", "New tab page / next / previous tab."), ("za / zR / zM", "Toggle fold / open all / close all."), (":copen / :cnext", "Open quickfix / next project-wide result."), (":lopen", "Open location list for this window.")]),
    ], "Use Space f f for file names, Space f g for project text, / for the current file, and Space f / for fuzzy filtering inside the current buffer."),
    ("Git, diagnostics, LSP & completion", "Some keys require the noted context", [
        ("Choose the right Git tool", [("Space h …", "Act on one changed hunk: stage, reset, preview, blame, diff."), ("Space g …", "Find Git information through Telescope."), ("Space l g", "Open the full LazyGit workflow.")]),
        ("Diagnostics & language features", [("[d / ]d", "Previous / next diagnostic; read its message."), ("Space l d", "Show the full diagnostic at the cursor."), ("Space l f", "Format the current LSP buffer; Markdown can use Prettier."), ("Space l i", "Toggle inlay hints when the server supports them.")]),
        ("Completion & snippets", [("Tab / Shift-Tab", "Jump forward / backward through an active snippet; otherwise type a tab."), ("Ctrl-n / Ctrl-p", "Next / previous built-in completion candidate."), ("Ctrl-y / Ctrl-e", "Accept / cancel a built-in completion candidate."), ("Ctrl-x Ctrl-o", "Request omnifunc completion where supported.")]),
    ], "Diagnostic means an editor-reported error, warning, or hint. LSP is the language-aware engine that supplies diagnostics, formatting, completion, navigation, and more."),
    ("Markdown, TODOs & writing tools", "Markdown / R Markdown mappings appear only in those buffers", [
        ("Markdown workflow", [("Preview", "Rendered, hybrid, or split preview helps read while editing."), ("Links", "Follow the current link or move through nearby links."), ("Tables & tasks", "Format a table or toggle a task checkbox."), ("Writing hygiene", "Project spell words, format-on-save, table mode, and linting are configured per project.")]),
        ("Spelling suggestions & dictionary", [("z=", "Show spelling suggestions for the misspelled word under the cursor; choose a number and press Enter."), ("]s / [s", "Jump to the next / previous misspelling."), ("zg", "Add the word under the cursor to the Vim dictionary."), ("Space mw / Space mW", "Add one / all misspellings to the project dictionary."), (":setlocal spell? / :setlocal spell", "Check whether spelling is active / enable it in this buffer.")]),
        ("Lint diagnostics & fixes", [("Space md", "Run markdownlint-cli2 manually in Markdown or R Markdown."), ("Save", "markdownlint-cli2 runs automatically after a Markdown or R Markdown write."), ("]d / [d", "Jump to the next / previous lint or LSP diagnostic."), ("Space ld", "Show the complete diagnostic at the cursor."), ("Space lf", "Format with Prettier; it is not a markdownlint fix-all command."), ("Fix a lint warning", "Edit the Markdown rule violation, then save to lint again; nvim-lint reports findings but does not apply markdownlint fixes here.")]),
        ("TODO discovery", [("TODO / FIX / FIXME / HACK", "Use clear comment markers so they are searchable."), ("Quickfix / location list", "Send discovered TODOs to a navigable list."), ("Autopairs", "Matching delimiters are configurable and intentionally disabled in picker/commit contexts.")]),
    ], "Markdown buffers automatically enable US English spell checking, soft wrapping, line breaks, and break indentation in this setup. Markdown linting is separate: markdownlint-cli2 supplies diagnostics, while Prettier formats the buffer."),
    ("Registers, visual mode & block edits", "Normal / Visual modes", [
        ("Registers: where copied text lives", [("\"0", "Latest yank; \"0p pastes the last copied text."), ("\"+", "System clipboard in this setup."), ("\"a", "Named register: \"ayy stores a line; \"ap pastes it."), ("\"_", "Black-hole register: delete without replacing the clipboard."), (":reg", "Inspect copied text and registers.")]),
        ("Visual mode", [("v / V", "Select characters / whole lines, then use an operator."), ("Ctrl-v", "Select a rectangle; I inserts on every selected line after Esc."), ("gv", "Reselect the previous visual selection."), ("~", "Swap selected text’s case."), ("J / gJ", "Join lines with / without adding a space.")]),
    ], "Your configuration uses unnamedplus, so ordinary yank, delete, and paste already share the system clipboard."),
    ("Sessions, dashboard & personal display", "Dashboard-only keys work on the Alpha start screen", [
        ("Sessions", [("Find session", "Restore a saved workspace."), ("Save session", "Persist the current layout and buffers."), ("What is saved", "Buffers, layout, current directory, terminals, folds, tab pages, and local options.")]),
        ("Dashboard", [("New file", "Start an empty editing buffer."), ("File / recent / text / projects", "Start common Telescope workflows from the dashboard."), ("Explorer / sessions / LazyGit", "Open a workspace tool before entering an editing buffer."), ("Plugin manager / quit", "Maintain plugins or exit Neovim.")]),
        ("Personal display", [("F2 / F3", "Toggle absolute / relative line numbers."), ("Clear highlighting", "Remove the visual highlight of the last search."), ("Indent guides", "Toggle indentation and its scope highlight."), ("Autopairs", "Toggle automatic bracket and quote pairing.")]),
    ], "Dashboard shortcuts are intentionally context-labeled in the generated appendix: use them from the Alpha start screen, not from an editing buffer."),
    ("Testing, debugging & code navigation", "Use context-aware tools to inspect and change behavior safely", [
        ("Testing loop", [("Run nearest test", "Start with the test closest to the cursor."), ("Run file / suite", "Widen scope after the nearest test is useful."), ("Test output", "Open output when a result needs diagnosis."), ("Toggle summary", "Keep test state visible while editing.")]),
        ("Debugging loop", [("Toggle breakpoint", "Mark the next place execution should pause."), ("Continue", "Run to the next breakpoint."), ("Step over / into / out", "Move through execution without losing the current state."), ("Inspect UI", "Open debugger panels for variables, stack, and console.")]),
        ("Code navigation", [("Definition / references", "Jump to where a symbol is defined or used."), ("Rename", "Apply a language-aware rename through the LSP."), ("Code action", "See available fixes and refactors."), ("Diagnostics", "Move through editor-reported problems before changing code.")]),
    ], "The complete appendix has the exact current keys. This page teaches the workflow first so it remains useful even when those keys evolve."),
]

# Stable Neovim reference material. These are deliberately separate from the
# configuration inventory: they are useful even when a command or API is not
# used by a current mapping, and make ordinary questions searchable in the PDF.
BUILTIN_COMMANDS = [
    ("Help & diagnosis", ":help {topic}", "Open built-in documentation; use :help user-manual for the full guide."),
    ("Help & diagnosis", ":helpgrep {pattern}", "Search all runtime help tags and text."),
    ("Help & diagnosis", ":checkhealth", "Run health checks for Neovim, providers, and plugins."),
    ("Help & diagnosis", ":messages", "Show recent notifications, errors, and command output."),
    ("Help & diagnosis", ":version", "Show the Neovim version and compiled features."),
    ("Files & buffers", ":edit {file}", "Open a file in the current window."),
    ("Files & buffers", ":enew", "Create a new empty buffer."),
    ("Files & buffers", ":write / :update", "Save the buffer; :update writes only when it changed."),
    ("Files & buffers", ":saveas {file}", "Write the buffer to a new file name."),
    ("Files & buffers", ":quit / :qall", "Close the current window / quit all of Neovim."),
    ("Files & buffers", ":writequit / :xit", "Save and close the current window."),
    ("Files & buffers", ":buffers / :buffer {name}", "List buffers / switch to a buffer by name or number."),
    ("Files & buffers", ":bnext / :bprevious", "Switch to the next / previous buffer."),
    ("Files & buffers", ":bdelete", "Unload the current buffer without necessarily closing its window."),
    ("Windows & tabs", ":split / :vsplit {file}", "Open a horizontal / vertical split, optionally with a file."),
    ("Windows & tabs", ":close / :only", "Close the current window / keep only the current window."),
    ("Windows & tabs", ":resize {height} / :vertical resize {width}", "Resize the current split."),
    ("Windows & tabs", ":tabnew {file}", "Open a new tab page, optionally with a file."),
    ("Windows & tabs", ":tabclose / :tabonly", "Close the current tab / keep only the current tab."),
    ("Windows & tabs", ":tabnext / :tabprevious", "Switch to the next / previous tab page."),
    ("Settings & mappings", ":set {option}?", "Inspect an option's current value."),
    ("Settings & mappings", ":set {option} / :set no{option}", "Enable / disable a boolean option."),
    ("Settings & mappings", ":setlocal {option}", "Change an option only for the current buffer or window."),
    ("Settings & mappings", ":verbose set {option}?", "Show an option's value and where it was last set."),
    ("Settings & mappings", ":map / :nmap / :imap", "List mappings, or mappings for Normal / Insert mode."),
    ("Settings & mappings", ":verbose nmap {key}", "Show a mapping and the file or plugin that defined it."),
    ("Settings & mappings", ":command", "List user-defined Ex commands."),
    ("Configuration", ":source $MYVIMRC", "Reload the current Neovim configuration file."),
    ("Configuration", ":lua {expression}", "Evaluate a Lua expression or call a Lua function."),
    ("Search & lists", ":nohlsearch", "Clear search highlighting without changing the search pattern."),
    ("Search & lists", ":copen / :cclose", "Open / close the quickfix list."),
    ("Search & lists", ":cnext / :cprevious", "Jump to the next / previous quickfix item."),
    ("Search & lists", ":lopen / :lclose", "Open / close the current window's location list."),
    ("Search & lists", ":lnext / :lprevious", "Jump to the next / previous location-list item."),
    ("Search & lists", ":vimgrep / :vimgrepadd", "Search files with Vim's regex engine and populate quickfix."),
    ("Editing", ":normal {keys}", "Execute Normal-mode keys on the current line or selected range."),
    ("Editing", ":undo / :redo", "Undo / redo a change from the command line."),
    ("Editing", ":retab", "Replace tab characters according to the current 'tabstop' settings."),
    ("Editing", ":sort [range]", "Sort lines in the current or selected range."),
    ("Plugins", ":Lazy", "Open Lazy.nvim's plugin manager."),
    ("Plugins", ":Mason", "Open Mason's package manager for LSP servers and tools."),
    ("Plugins", ":Telescope {picker}", "Open a Telescope picker such as find_files, live_grep, buffers, or help_tags."),
]

BUILTIN_FUNCTIONS = [
    ("Neovim Lua", "vim.cmd(\"{ex-command}\")", "Run an Ex command from Lua."),
    ("Neovim Lua", "vim.keymap.set(mode, lhs, rhs, opts)", "Create a keymap with a description, buffer, and other options."),
    ("Neovim Lua", "vim.notify(message, level)", "Show an informational, warning, or error notification."),
    ("Neovim Lua", "vim.schedule(callback)", "Defer a callback until it is safe to update the UI."),
    ("Buffers & windows", "vim.api.nvim_get_current_buf()", "Get the current buffer number."),
    ("Buffers & windows", "vim.api.nvim_buf_get_name(buf)", "Get a buffer's full file name."),
    ("Buffers & windows", "vim.api.nvim_buf_get_lines(buf, start, end, strict)", "Read lines from a buffer; line indexes are zero-based."),
    ("Buffers & windows", "vim.api.nvim_buf_set_lines(buf, start, end, strict, lines)", "Replace a range of buffer lines."),
    ("Buffers & windows", "vim.api.nvim_win_get_cursor(win)", "Get a window cursor as { line, column }."),
    ("Buffers & windows", "vim.api.nvim_win_set_cursor(win, position)", "Move a window cursor programmatically."),
    ("Autocommands", "vim.api.nvim_create_augroup(name, opts)", "Create or reset a named autocommand group."),
    ("Autocommands", "vim.api.nvim_create_autocmd(event, opts)", "Run a callback on events such as BufWritePost, FileType, or LspAttach."),
    ("Commands", "vim.api.nvim_create_user_command(name, callback, opts)", "Define a custom :Command that users can run."),
    ("Vim functions", "vim.fn.expand(\"%:p\")", "Expand the current file, cursor word, or another Vim expression."),
    ("Vim functions", "vim.fn.getcwd()", "Return Neovim's current working directory."),
    ("Vim functions", "vim.fn.executable(\"tool\")", "Check whether an executable is available on PATH."),
    ("Vim functions", "vim.fn.exepath(\"tool\")", "Return the resolved path of an executable."),
    ("Vim functions", "vim.fn.stdpath(\"config\")", "Find Neovim's config, data, state, or cache directory."),
    ("Vim functions", "vim.fn.system({ command, args })", "Run an external command and capture its output."),
    ("Vim functions", "vim.fn.fnameescape(path)", "Escape a file name before passing it to an Ex command."),
    ("Vim functions", "vim.fn.spellbadword()", "Return the misspelled word at the cursor and its spelling type."),
    ("Filesystem", "vim.fs.find(names, opts)", "Find files or directories upward or downward from a path."),
    ("Filesystem", "vim.fs.root(path, markers)", "Find a project root using marker files such as .git or pyproject.toml."),
    ("Diagnostics", "vim.diagnostic.open_float()", "Show the complete diagnostic message at the cursor."),
    ("Diagnostics", "vim.diagnostic.jump({ count = 1, float = true })", "Jump to the next or previous diagnostic and optionally show it."),
    ("Diagnostics", "vim.diagnostic.get(buf, opts)", "Read diagnostics for a buffer, namespace, severity, or range."),
    ("LSP", "vim.lsp.buf.hover()", "Request hover documentation for the symbol under the cursor."),
    ("LSP", "vim.lsp.buf.definition()", "Jump to the definition of the symbol under the cursor."),
    ("LSP", "vim.lsp.buf.references()", "List references to the symbol under the cursor."),
    ("LSP", "vim.lsp.buf.rename()", "Rename a symbol through the attached language server."),
    ("LSP", "vim.lsp.buf.code_action()", "Request available fixes and refactors from the language server."),
    ("LSP", "vim.lsp.buf.format({ async = true })", "Format the current buffer through a formatter or LSP."),
    ("LSP", "vim.lsp.get_clients({ bufnr = buf })", "List language-server clients attached to a buffer."),
    ("LSP", "vim.lsp.enable(servers)", "Enable a list of configured language servers."),
    ("Completion", "vim.lsp.completion.get()", "Request completion items at the cursor."),
    ("Completion", "vim.lsp.inlay_hint.enable(enabled, opts)", "Enable or disable inline type and parameter hints."),
    ("Configured tools", "require(\"lint\").try_lint()", "Run the configured linter and publish its findings as diagnostics."),
    ("Configured tools", "require(\"conform\").format()", "Run the configured formatter, such as Prettier for Markdown."),
    ("Configured tools", "require(\"telescope.builtin\").find_files()", "Open Telescope's file finder from Lua."),
    ("Configured tools", "require(\"nvim-tree.api\").tree.toggle()", "Open or close the configured file explorer."),
    ("Configured tools", "require(\"gitsigns\").stage_hunk()", "Stage the Git hunk under the cursor."),
    ("Configured tools", "require(\"neotest\").run.run()", "Run the test nearest the cursor."),
    ("Configured tools", "require(\"dap\").continue()", "Start or continue a debugger session."),
]

INDEX_PROMPTS = [
    ("Files & project navigation", "find files, project text, recent files, buffers, help, keymaps, explorer"),
    ("Editing", "change, delete, copy, paste, repeat, register, text object, visual block"),
    ("Commands & Lua functions", "Ex command, command mode, set, source, lua, function, vim.api, vim.fn, vim.lsp, vim.diagnostic, plugin API"),
    ("Code help", "diagnostic, format, completion, inlay hint, LSP, snippet, code action, rename, definition"),
    ("Git", "hunk, stage, reset, blame, diff, branch, commit, LazyGit"),
    ("Writing, spelling & lint fixes", "Markdown, link, preview, table, spellcheck, misspelled word, spelling suggestion, dictionary, TODO, lint, markdownlint, diagnostic, warning, fix, format, Prettier"),
]
